sudo: false
language: perl
matrix:
    fast_finish: true
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
before_install:
    - "cpanm -qn List::MoreUtils Moo Path::Tiny Text::CSV Test::More Test::Warnings Test::Requires::Git Devel::Cover::Report::Codecov"
script:
    perl Makefile.PL && cover -test -report codecov
